Sky.Blog/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sky.Models;
using Sky.Blog.Core;
using Sky.Blog.Helper;
using XCode;

namespace Sky.Blog.Controllers
{
    public class ArticleController : BaseController
    {
        /// <summary>
        /// 文章列表页(带上搜索功能)
        /// </summary>
        /// <param name="category"></param>
        /// <param name="state"></param>
        /// <param name="title"></param>
        /// <param name="pageIndex"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        public ActionResult List(int? category,int? state,string title = "", int pageIndex = 1, int pageSize = 2)
        {
            #region 构造查询表达式
            var exp = new WhereExpression();
            exp &= Article._.IsDel == 0;
            if (category.HasValue&category!=0)
            {
                exp &= Article._.CategoryId == category;
                ViewBag.CagegotyId = category;
            }
            if (!title.IsNullOrEmpty())
            {
                exp &= Article._.Title.Contains(title);
                ViewBag.ArticleTitle = title;
            }
            if (state.HasValue&state!=0)
            {
                exp &= Article._.State==state;
                ViewBag.State = state;
            }
            #endregion
            var allArticle = Article.FindAll(exp, Article._.IsTop+" desc,Sort",null,(pageIndex - 1)* pageSize, pageSize);
            int count = Article.FindCount(exp);
            ViewBag.Categories = Category.FindAll();
            ViewBag.PageNo = pageIndex;
            ViewBag.TotalPage = Math.Ceiling((double)count/pageSize);           
            return View(allArticle);
        }
        /// <summary>
        /// 添加文章
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            var p = new Article();
            ViewBag.Categories = Category.FindAll();
            return View("Edit", p);
        }
        /// <summary>
        /// 编辑文章
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult Edit(Article model)
        {
            if (model!=null)
            {
                ViewBag.Categories = Category.FindAll();             
                return View(model);
            }
            return RedirectToAction("Error500", "ErrorPage");
        }
        /// <summary>
        /// 保存文章
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [ValidateInputAttribute(false)]
        public ActionResult Save(Article model)
        {
            if (model.ID == 0)
            {
                model.CreateTime=DateTime.Now;
            }
            model.Save();
            return RedirectToAction("List");
        }
        /// <summary>
        /// 删除文章
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(Article model)
        {
            model.Delete();
            return Json(new AjaxResult{Msg="删除成功"});
        }
    }
}

Sky.Blog/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sky.Blog.Helper;
using Sky.Models;
namespace Sky.Blog.Controllers
{
    public class CategoryController : BaseController
    {
        // GET: Category
        public ActionResult List(int pageNo = 1, int pageSize = 15)
        {
            var setting = GetSetting();
            if (setting != null)
                pageSize = setting.ManagePageSize;
            var totalRows = Category.FindAll("1=1",Category._.IsTop+" desc,"+Category._.Sort,null,(pageNo-1)*pageSize,pageSize);
            return View(totalRows);
        }

        public ActionResult Create()
        {
            return View("Edit",new Category());
        }

        public ActionResult Edit(Category model)
        {
            return View(model);
        }

        public ActionResult Save(Category model)
        {
            if (model == null)
                throw new ArgumentNullException(nameof(model));          
            if(model.ID==0)model.CreateTime=DateTime.Now;
            model.Save();
            return RedirectToAction("List");
        }
        [HttpPost]
        public ActionResult Delete(Category model)
        {          
            var exists = model.Articles.Count>0;
            if (exists)
                return Json(new { success = false, message = "该分类下存在文章，请先删除文章！" });
            model.Delete();
            return Json(new AjaxResult { Msg = "删除成功" });
        }

        [HttpGet]
        public ActionResult CheckName()
        {
            var value = Request["name"];           
            var flag = Category.FindCount(Category._.CategoryName==value.Trim()) > 0;          
            return Json(new { success = flag, message = flag ? "分类名称已存在" : "名称可用！" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Sky.Blog/Controllers/SettingController.cs
using System.Web.Mvc;
using Sky.Blog.Configs.Models;

namespace Sky.Blog.Controllers
{
    public class SettingController : BaseController
    {
        // GET: Setting
        public ActionResult BasicSetting()
        {
            var setting = Configs.ConfigHelper.GetBasicConfig();

            return View(setting);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateBasicSetting(Setting model)
        {
            Configs.ConfigHelper.SetBasicConfig(model);
            return RedirectToAction("BasicSetting");
        }
    }
}

Sky.Blog/Views/Shared/_LayoutPage.cshtml
@using Sky.Blog.Configs
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="keywords" content="@ViewBag.Keywords" />
    <meta name="description" content="@ViewBag.Description" />
    <meta name="author" content="@ViewBag.Author" />
    <title>@ViewBag.Title - 博客</title>
    <link href="~/Plugins/layui/css/layui.css" rel="stylesheet" />
    <link href="~/Content/css/main.css" rel="stylesheet" />
</head>
<body class="blog-body">
    <div class="layui-header blog-header">
        <div class="blog-container">
            <div class="blog-header-title">
                @{
                    var name = "初学者";
                    var setting = ConfigHelper.GetBasicConfig();
                    if (setting != null)
                    {
                        name = setting.WebsiteName;
                    }
                }
                <p><a href="/" style="color:#ffffff;">@name</a></p>
            </div>
            <div class="blog-header-menu">
                <div class="blog-header-menu-icon">
                    <i class="layui-icon">&#xe60f;</i>
                </div>
                <ul class="layui-nav layui-nav-tree blog-header-menu-nav">
                    <li class="layui-nav-item"><a href="@Url.Action("List","Home")">首页</a></li>
                    @*<li class="layui-nav-item"><a href="@Url.Action("Archive", "Home")">文章归档</a></li>*@
                    <li class="layui-nav-item"><a href="@Url.Action("About","Home")">关于我</a></li>
                </ul>
            </div>
            <ul class="layui-nav blog-header-nav">
                <li class="layui-nav-item"><a href="@Url.Action("List","Home")">首页</a></li>
                @*<li class="layui-nav-item"><a href="@Url.Action("Archive", "Home")">文章归档</a></li>*@
                <li class="layui-nav-item"><a href="@Url.Action("About","Home")">关于我</a></li>
            </ul>
        </div>
    </div>
    <div class="layui-main blog-container">
        @RenderBody()
    </div>
    <div class="layui-footer">
        <div class="blog-footer-main">
            <p>世界之大我却不知其折或远!</p>
            <p style="margin-top:5px">©2016-@DateTime.Now.ToString("yyyy")&nsub;&nbsp;<a href="http://www.shadameng.xyz">www.shadameng.xyz</a></p>
            <p style="margin-top:5px">桂ICP备17004359号</p>
        </div>
    </div>
    <script src="~/Plugins/layui/layui.js"></script>
    <script>

        layui.use(['util', 'jquery'], function () {
            var util = layui.util, $ = layui.jquery;

            util.fixbar();

            $('.blog-header-menu-icon').on('click', function () {
                var $nav = $('.blog-header-menu-nav');
                $nav.toggle();
            });
        });


    </script>
    @RenderSection("scripts", false)
</body>
</html>

Sky.Blog/Views/Shared/_ManageLayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>@ViewBag.Title - 后台管理</title>
    <link href="~/Plugins/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Plugins/layui/css/layui.css" rel="stylesheet" />
    <link href="~/Content/css/global.css" rel="stylesheet" />
    @RenderSection("styles", false)
</head>
<body class="layui-body-admin">
    <div class="layui-layout-admin">
        <div class="layui-header">
            <a href="#" class="logo layui-left"><img src="" alt="">傻大蒙</a>
        </div>
        <div class="layui-side" style="background-color:#393D49; color:white;">
            <div style="height: 100px;padding: 5px;line-height: 40px;text-align: center;">
                <p>欢迎您，主人</p>
                <a href="@Url.Action("SignOut","Account")" style="border-radius:8px;" class="layui-btn layui-btn-small">退出</a>
            </div>
            <ul class="layui-nav layui-nav-tree">
                <li class="layui-nav-item layui-nav-title item-show" nav-item-num="4">
                    <a>内容管理<i class="layui-icon layui-right">&#xe619;</i></a>
                </li>
                <li class="layui-nav-item">
                    <a href="@Url.Action("List","Article")">文章管理</a>
                </li>
                <li class="layui-nav-item">
                    <a href="@Url.Action("List","Category")">分类管理</a>
                </li>
                <li class="layui-nav-item ">
                    <a href="javascript:;">留言管理</a>
                </li>
                @*<li class="layui-nav-item">
                    <a href="@Url.Action("List","Log")">操作日志</a>
                </li>*@
                <li class="layui-nav-item">
                    <a href="@Url.Action("BasicSetting","Setting")">设置</a>
                </li>
            </ul>
        </div>
        <div class="layui-body">
            @RenderBody()
        </div>
        <div class="layui-footer">
            <div class="layui-main">
                Sky © <a href="http://www.shadameng.xyz">www.shadameng.xyz</a>
            </div>
        </div>
    </div>
    <script src="~/Plugins/layui/layui.js"></script>
    <script src="~/Scripts/global.js"></script>
    @RenderSection("scripts", false)
</body>
</html>